//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var ttypes = module.exports = {};
if (typeof com === 'undefined') {
  com = {};
}
if (typeof com.dellitt === 'undefined') {
  com.dellitt = {};
}
if (typeof com.dellitt.thrift === 'undefined') {
  com.dellitt.thrift = {};
}
