//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./Calculator_types');
//HELPER FUNCTIONS AND STRUCTURES

com.dellitt.thrift.Calculator_add_args = function(args) {
  this.first = null;
  this.second = null;
  if (args) {
    if (args.first !== undefined) {
      this.first = args.first;
    }
    if (args.second !== undefined) {
      this.second = args.second;
    }
  }
};
com.dellitt.thrift.Calculator_add_args.prototype = {};
com.dellitt.thrift.Calculator_add_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case -1:
      if (ftype == Thrift.Type.I64) {
        this.first = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case -2:
      if (ftype == Thrift.Type.I64) {
        this.second = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.dellitt.thrift.Calculator_add_args.prototype.write = function(output) {
  output.writeStructBegin('Calculator_add_args');
  if (this.first !== null && this.first !== undefined) {
    output.writeFieldBegin('first', Thrift.Type.I64, -1);
    output.writeI64(this.first);
    output.writeFieldEnd();
  }
  if (this.second !== null && this.second !== undefined) {
    output.writeFieldBegin('second', Thrift.Type.I64, -2);
    output.writeI64(this.second);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.dellitt.thrift.Calculator_add_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
com.dellitt.thrift.Calculator_add_result.prototype = {};
com.dellitt.thrift.Calculator_add_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I64) {
        this.success = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.dellitt.thrift.Calculator_add_result.prototype.write = function(output) {
  output.writeStructBegin('Calculator_add_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I64, 0);
    output.writeI64(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.dellitt.thrift.Calculator_subtract_args = function(args) {
  this.first = null;
  this.second = null;
  if (args) {
    if (args.first !== undefined) {
      this.first = args.first;
    }
    if (args.second !== undefined) {
      this.second = args.second;
    }
  }
};
com.dellitt.thrift.Calculator_subtract_args.prototype = {};
com.dellitt.thrift.Calculator_subtract_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case -1:
      if (ftype == Thrift.Type.I64) {
        this.first = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case -2:
      if (ftype == Thrift.Type.I64) {
        this.second = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.dellitt.thrift.Calculator_subtract_args.prototype.write = function(output) {
  output.writeStructBegin('Calculator_subtract_args');
  if (this.first !== null && this.first !== undefined) {
    output.writeFieldBegin('first', Thrift.Type.I64, -1);
    output.writeI64(this.first);
    output.writeFieldEnd();
  }
  if (this.second !== null && this.second !== undefined) {
    output.writeFieldBegin('second', Thrift.Type.I64, -2);
    output.writeI64(this.second);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.dellitt.thrift.Calculator_subtract_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
com.dellitt.thrift.Calculator_subtract_result.prototype = {};
com.dellitt.thrift.Calculator_subtract_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I64) {
        this.success = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.dellitt.thrift.Calculator_subtract_result.prototype.write = function(output) {
  output.writeStructBegin('Calculator_subtract_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I64, 0);
    output.writeI64(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.dellitt.thrift.Calculator_multiply_args = function(args) {
  this.first = null;
  this.second = null;
  if (args) {
    if (args.first !== undefined) {
      this.first = args.first;
    }
    if (args.second !== undefined) {
      this.second = args.second;
    }
  }
};
com.dellitt.thrift.Calculator_multiply_args.prototype = {};
com.dellitt.thrift.Calculator_multiply_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case -1:
      if (ftype == Thrift.Type.I64) {
        this.first = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case -2:
      if (ftype == Thrift.Type.I64) {
        this.second = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.dellitt.thrift.Calculator_multiply_args.prototype.write = function(output) {
  output.writeStructBegin('Calculator_multiply_args');
  if (this.first !== null && this.first !== undefined) {
    output.writeFieldBegin('first', Thrift.Type.I64, -1);
    output.writeI64(this.first);
    output.writeFieldEnd();
  }
  if (this.second !== null && this.second !== undefined) {
    output.writeFieldBegin('second', Thrift.Type.I64, -2);
    output.writeI64(this.second);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.dellitt.thrift.Calculator_multiply_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
com.dellitt.thrift.Calculator_multiply_result.prototype = {};
com.dellitt.thrift.Calculator_multiply_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I64) {
        this.success = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.dellitt.thrift.Calculator_multiply_result.prototype.write = function(output) {
  output.writeStructBegin('Calculator_multiply_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I64, 0);
    output.writeI64(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.dellitt.thrift.Calculator_divide_args = function(args) {
  this.first = null;
  this.second = null;
  if (args) {
    if (args.first !== undefined) {
      this.first = args.first;
    }
    if (args.second !== undefined) {
      this.second = args.second;
    }
  }
};
com.dellitt.thrift.Calculator_divide_args.prototype = {};
com.dellitt.thrift.Calculator_divide_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case -1:
      if (ftype == Thrift.Type.I64) {
        this.first = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case -2:
      if (ftype == Thrift.Type.I64) {
        this.second = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.dellitt.thrift.Calculator_divide_args.prototype.write = function(output) {
  output.writeStructBegin('Calculator_divide_args');
  if (this.first !== null && this.first !== undefined) {
    output.writeFieldBegin('first', Thrift.Type.I64, -1);
    output.writeI64(this.first);
    output.writeFieldEnd();
  }
  if (this.second !== null && this.second !== undefined) {
    output.writeFieldBegin('second', Thrift.Type.I64, -2);
    output.writeI64(this.second);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.dellitt.thrift.Calculator_divide_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
com.dellitt.thrift.Calculator_divide_result.prototype = {};
com.dellitt.thrift.Calculator_divide_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I64) {
        this.success = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.dellitt.thrift.Calculator_divide_result.prototype.write = function(output) {
  output.writeStructBegin('Calculator_divide_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I64, 0);
    output.writeI64(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.dellitt.thrift.CalculatorClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
com.dellitt.thrift.CalculatorClient.prototype = {};
com.dellitt.thrift.CalculatorClient.prototype.add = function(first, second, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_add(first, second);
};

com.dellitt.thrift.CalculatorClient.prototype.send_add = function(first, second) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('add', Thrift.MessageType.CALL, this.seqid);
  var args = new com.dellitt.thrift.Calculator_add_args();
  args.first = first;
  args.second = second;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

com.dellitt.thrift.CalculatorClient.prototype.recv_add = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new com.dellitt.thrift.Calculator_add_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('add failed: unknown result');
};
com.dellitt.thrift.CalculatorClient.prototype.subtract = function(first, second, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_subtract(first, second);
};

com.dellitt.thrift.CalculatorClient.prototype.send_subtract = function(first, second) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('subtract', Thrift.MessageType.CALL, this.seqid);
  var args = new com.dellitt.thrift.Calculator_subtract_args();
  args.first = first;
  args.second = second;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

com.dellitt.thrift.CalculatorClient.prototype.recv_subtract = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new com.dellitt.thrift.Calculator_subtract_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('subtract failed: unknown result');
};
com.dellitt.thrift.CalculatorClient.prototype.multiply = function(first, second, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_multiply(first, second);
};

com.dellitt.thrift.CalculatorClient.prototype.send_multiply = function(first, second) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('multiply', Thrift.MessageType.CALL, this.seqid);
  var args = new com.dellitt.thrift.Calculator_multiply_args();
  args.first = first;
  args.second = second;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

com.dellitt.thrift.CalculatorClient.prototype.recv_multiply = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new com.dellitt.thrift.Calculator_multiply_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('multiply failed: unknown result');
};
com.dellitt.thrift.CalculatorClient.prototype.divide = function(first, second, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_divide(first, second);
};

com.dellitt.thrift.CalculatorClient.prototype.send_divide = function(first, second) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('divide', Thrift.MessageType.CALL, this.seqid);
  var args = new com.dellitt.thrift.Calculator_divide_args();
  args.first = first;
  args.second = second;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

com.dellitt.thrift.CalculatorClient.prototype.recv_divide = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new com.dellitt.thrift.Calculator_divide_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('divide failed: unknown result');
};
com.dellitt.thrift.CalculatorProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
com.dellitt.thrift.CalculatorProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

com.dellitt.thrift.CalculatorProcessor.prototype.process_add = function(seqid, input, output) {
  var args = new com.dellitt.thrift.Calculator_add_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.add(args.first, args.second, function (err, result) {
    var result = new com.dellitt.thrift.Calculator_add_result((err != null ? err : {success: result}));
    output.writeMessageBegin("add", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

com.dellitt.thrift.CalculatorProcessor.prototype.process_subtract = function(seqid, input, output) {
  var args = new com.dellitt.thrift.Calculator_subtract_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.subtract(args.first, args.second, function (err, result) {
    var result = new com.dellitt.thrift.Calculator_subtract_result((err != null ? err : {success: result}));
    output.writeMessageBegin("subtract", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

com.dellitt.thrift.CalculatorProcessor.prototype.process_multiply = function(seqid, input, output) {
  var args = new com.dellitt.thrift.Calculator_multiply_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.multiply(args.first, args.second, function (err, result) {
    var result = new com.dellitt.thrift.Calculator_multiply_result((err != null ? err : {success: result}));
    output.writeMessageBegin("multiply", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

com.dellitt.thrift.CalculatorProcessor.prototype.process_divide = function(seqid, input, output) {
  var args = new com.dellitt.thrift.Calculator_divide_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.divide(args.first, args.second, function (err, result) {
    var result = new com.dellitt.thrift.Calculator_divide_result((err != null ? err : {success: result}));
    output.writeMessageBegin("divide", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

